# Generated by Django 4.0 on 2021-12-29 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_course_student_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('subscriber', 'Student subscriber'), ('unsubscribed', 'Student unsubscribed'), ('studying', 'Student studying')], default='subscriber', max_length=30),
        ),
    ]
